version: "3.9"
services:
  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - .db-data/:/data/db
    deploy:
      resources:
        limits:
          memory: 2000M
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile-API
    depends_on:
      - database
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.db-data/
    deploy:
      resources:
        limits:
          memory: 2000M
